# Site settings
title: Jekyll Semantic UI Theme | OpenTheme.co
tagline: Create Awesome Websites on GitHub 
email: sehgal.manav@gmail.com
copyright: Manav Sehgal
description: > # this means to ignore newlines until "url:"
  Starter theme using Semantic UI and Jekyll for creating awesome
  websites on GitHub Pages.

url: "http://opentheme.co" # the base hostname & protocol for your site
twitter_username: manavsehgal
github_username:  manavsehgal

permalink: pretty

# List Limits
tags_limit: 10          # Alphabetical sort
categories_limit: 10    # Alphabetical sort
recent_posts_limit: 5   # Chronological sort

# Layout configuration
pagebar: true
postbar: true

# Features
reading_time: true    # Show est. reading time for posts

# Embeds
disqus_name: opentheme  # Your site name at Disqus
youtube_controls: 0  # Turn on=1/off=0 Youtube player features when embedding videos

# Build settings
markdown: kramdown

