# Site settings
title: Semantic Jekyll Theme by OpenStart.co
tagline: Create Awesome Websites on GitHub 
email: sehgal.manav@gmail.com
copyright: OpenStart.co
description: > # this means to ignore newlines until "url:"
  Starter theme using Semantic UI and Jekyll for creating awesome
  websites on GitHub Pages.

url: "http://opentheme.co" # the base hostname & protocol for your site
twitter_username: manavsehgal
github_username:  manavsehgal

# Build settings
markdown: kramdown

