# Site settings
title: Semantic Jekyll Theme by OpenStart.co
tagline: Create Awesome Websites on GitHub 
email: sehgal.manav@gmail.com
copyright: OpenStart.co
description: > # this means to ignore newlines until "baseurl:"
  Starter theme using Semantic UI and Jekyll for creating awesome
  websites on GitHub Pages.

# Only required for Project GitHub Pages
baseurl: "/semantic-jekyll-theme" # the subpath of your site, e.g. /blog/

url: "http://open-start.github.io" # the base hostname & protocol for your site
twitter_username: manavsehgal
github_username:  manavsehgal

# Build settings
markdown: kramdown

